//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int ProdutoID { get; set; }
        public int IDCategoria { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public decimal ValorAtual { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
